---
kind: pipeline
type: docker
name: 测试 Drone

steps:
  - name: build-and-publish-to-ecr
    image: registry.k8s.intra.knownsec.com/xn-base/drone-aws-ecr:1.1.0-rc4
    settings:
      harbor_username:
        from_secret: harbor_username
      harbor_password:
        from_secret: harbor_password
      aws_access_key_id:
        from_secret: aws_access_key
      aws_secret_access_key:
        from_secret: aws_secret_key
      aws_region: ap-northeast-1
      repo: 776237048507.dkr.ecr.ap-northeast-1.amazonaws.com/oc-server
      tag: latest

trigger:
  event:
    - pull_request
    - push
  branch:
    - master